TEMPLATE = app
CONFIG += console c++11
CONFIG -= app_bundle
CONFIG -= qt

SOURCES += \
        commands/thermostat/thermostatsettemperaturecommand.cpp \
        commands/appliancecommand/applianceoffcommand.cpp \
        commands/appliancecommand/applianceoncommand.cpp \
        commands/ceilingfan/ceilingfanhighcommand.cpp \
        commands/ceilingfan/ceilingfanlowcommand.cpp \
        commands/ceilingfan/ceilingfanmediumcommand.cpp \
        commands/ceilingfan/ceilingfanoffcommand.cpp \
        commands/ceilinglight/ceilinglightdimcommand.cpp \
        commands/ceilinglight/ceilinglightoffcommand.cpp \
        commands/ceilinglight/ceilinglightoncommand.cpp \
        commands/faucetcontrol/faucetcontrolclosecommand.cpp \
        commands/faucetcontrol/faucetcontrolopencommand.cpp \
        commands/garagedoor/garagedoordowncommand.cpp \
        commands/garagedoor/garagedoorlightoffcommand.cpp \
        commands/garagedoor/garagedoorlightoncommand.cpp \
        commands/garagedoor/garagedoorstopcommand.cpp \
        commands/garagedoor/garagedoorupcommand.cpp \
        commands/gardenlight/gardenlightmanualoffcommand.cpp \
        commands/gardenlight/gardenlightmanualoncommand.cpp \
        commands/gardenlight/gardenlightsetdawntimecommand.cpp \
        commands/gardenlight/gardenlightsetdusttimecommand.cpp \
        commands/hottub/hottubcirculatecommand.cpp \
        commands/hottub/hottubjetsoffcommand.cpp \
        commands/hottub/hottubjetsoncommand.cpp \
        commands/hottub/hottubsettemperaturecommand.cpp \
        commands/lightcommand/lightoffcommand.cpp \
        commands/lightcommand/lightoncommand.cpp \
        commands/nocommand.cpp \
        commands/outdoorlight/outdoorlightoffcommand.cpp \
        commands/outdoorlight/outdoorlightoncommand.cpp \
        commands/securitycontrol/securitycontrolarmcommand.cpp \
        commands/securitycontrol/securitycontroldisarmcommand.cpp \
        commands/sprinkler/sprinklerwateroffcommand.cpp \
        commands/sprinkler/sprinklerwateroncommand.cpp \
        commands/stereo/stereooffcommand.cpp \
        commands/stereo/stereooncommand.cpp \
        commands/stereo/stereosetcdcommand.cpp \
        commands/stereo/stereosetdvdcommand.cpp \
        commands/stereo/stereosetradiocommand.cpp \
        commands/stereo/stereosetvolumecommand.cpp \
        commands/tv/tvoffcommand.cpp \
        commands/tv/tvoncommand.cpp \
        commands/tv/tvsetinputchannel.cpp \
        commands/tv/tvsetvolumecommand.cpp \
        devices/appliancecontrol.cpp \
        devices/ceilingfan.cpp \
        devices/ceilinglight.cpp \
        devices/faucetcontrol.cpp \
        devices/garagedoor.cpp \
        devices/gardenlight.cpp \
        devices/hottub.cpp \
        devices/light.cpp \
        devices/outdoorlight.cpp \
        devices/securitycontrol.cpp \
        devices/sprinkler.cpp \
        devices/stereo.cpp \
        devices/thermostat.cpp \
        devices/tv.cpp \
        interfaces/icommand.cpp \
        main.cpp \
        remotecontrol.cpp

HEADERS += \
    commands/thermostat/thermostatsettemperaturecommand.h \
    commands/appliancecommand/applianceoffcommand.h \
    commands/appliancecommand/applianceoncommand.h \
    commands/ceilingfan/ceilingfanhighcommand.h \
    commands/ceilingfan/ceilingfanlowcommand.h \
    commands/ceilingfan/ceilingfanmediumcommand.h \
    commands/ceilingfan/ceilingfanoffcommand.h \
    commands/ceilinglight/ceilinglightdimcommand.h \
    commands/ceilinglight/ceilinglightoffcommand.h \
    commands/ceilinglight/ceilinglightoncommand.h \
    commands/faucetcontrol/faucetcontrolclosecommand.h \
    commands/faucetcontrol/faucetcontrolopencommand.h \
    commands/garagedoor/garagedoordowncommand.h \
    commands/garagedoor/garagedoorlightoffcommand.h \
    commands/garagedoor/garagedoorlightoncommand.h \
    commands/garagedoor/garagedoorstopcommand.h \
    commands/garagedoor/garagedoorupcommand.h \
    commands/gardenlight/gardenlightmanualoffcommand.h \
    commands/gardenlight/gardenlightmanualoncommand.h \
    commands/gardenlight/gardenlightsetdawntimecommand.h \
    commands/gardenlight/gardenlightsetdusttimecommand.h \
    commands/hottub/hottubcirculatecommand.h \
    commands/hottub/hottubjetsoffcommand.h \
    commands/hottub/hottubjetsoncommand.h \
    commands/hottub/hottubsettemperaturecommand.h \
    commands/lightcommand/lightoffcommand.h \
    commands/lightcommand/lightoncommand.h \
    commands/nocommand.h \
    commands/outdoorlight/outdoorlightoffcommand.h \
    commands/outdoorlight/outdoorlightoncommand.h \
    commands/securitycontrol/securitycontrolarmcommand.h \
    commands/securitycontrol/securitycontroldisarmcommand.h \
    commands/sprinkler/sprinklerwateroffcommand.h \
    commands/sprinkler/sprinklerwateroncommand.h \
    commands/stereo/stereooffcommand.h \
    commands/stereo/stereooncommand.h \
    commands/stereo/stereosetcdcommand.h \
    commands/stereo/stereosetdvdcommand.h \
    commands/stereo/stereosetradiocommand.h \
    commands/stereo/stereosetvolumecommand.h \
    commands/tv/tvoffcommand.h \
    commands/tv/tvoncommand.h \
    commands/tv/tvsetinputchannel.h \
    commands/tv/tvsetvolumecommand.h \
    devices/appliancecontrol.h \
    devices/ceilingfan.h \
    devices/ceilinglight.h \
    devices/faucetcontrol.h \
    devices/garagedoor.h \
    devices/gardenlight.h \
    devices/hottub.h \
    devices/light.h \
    devices/outdoorlight.h \
    devices/securitycontrol.h \
    devices/sprinkler.h \
    devices/stereo.h \
    devices/thermostat.h \
    devices/tv.h \
    interfaces/icommand.h \
    remotecontrol.h
